language: objective-c
before_script:
    - export LANG=en_US.UTF-8
before_install:
    - brew update
    - brew uninstall xctool
    - brew install xctool
script:
    - xctool -project KiteJSONValidator.xcodeproj -scheme KiteJSONValidatorTests -sdk iphonesimulator test ONLY_ACTIVE_ARCH=NO
