language: objective-c
before_script:
    - export LANG=en_US.UTF-8
script:
    - set -o pipefail && xcodebuild clean test -project KiteJSONValidator.xcodeproj -scheme KiteJSONValidatorTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty